
name: just_one_app
description: A simple Flutter app to show random images from a folder.

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  file_picker: ^6.1.1
  photo_view: ^0.14.0
  audioplayers: ^5.2.1
  shared_preferences: ^2.2.2

flutter:
  uses-material-design: true
  assets:
    - assets/shuffle.mp3
